-- ======================================================
-- INSERTION DES DONNEES
-- ======================================================

-- Points
DELETE FROM POINT;
INSERT INTO POINT (id, nom) VALUES (1, 'Tananarive');
INSERT INTO POINT (id, nom) VALUES (2, 'Sambaina');
INSERT INTO POINT (id, nom) VALUES (3, 'Antsirabe');
INSERT INTO POINT (id, nom) VALUES (4, 'Ampefy');
DROP SEQUENCE SEQ_POINT;
CREATE SEQUENCE SEQ_POINT START WITH 5 INCREMENT BY 1 NOCACHE;

-- Chemins
DELETE FROM CHEMIN;
INSERT INTO CHEMIN VALUES (1, 'Tana-Sambaina', 1, 2, 200, 10, 'DOUBLE');
INSERT INTO CHEMIN VALUES (2, 'Sambaina-Antsirabe', 2, 3, 120, 10, 'DOUBLE');
INSERT INTO CHEMIN VALUES (3, 'Tana-Ampefy', 1, 4, 163, 10, 'DOUBLE');
INSERT INTO CHEMIN VALUES (4, 'Ampefy-Sambaina', 4, 2, 88, 10, 'DOUBLE');
DROP SEQUENCE SEQ_CHEMIN;
CREATE SEQUENCE SEQ_CHEMIN START WITH 5 INCREMENT BY 1 NOCACHE;

-- Dommages
DELETE FROM DOMMAGE;

-- 1 dommage
INSERT INTO DOMMAGE VALUES (1, 1, 30, 77, 0.22);
INSERT INTO DOMMAGE VALUES (2, 2, 12, 25, 0.66);
INSERT INTO DOMMAGE VALUES (3, 2, 56, 70, 0.11);
INSERT INTO DOMMAGE VALUES (4, 4, 25, 32, 0.15);

-- INSERT INTO DOMMAGE VALUES (2, 4, 50, 80, 0.25);

DROP SEQUENCE SEQ_DOMMAGE;
CREATE SEQUENCE SEQ_DOMMAGE START WITH 5 INCREMENT BY 1 NOCACHE;

-- Pauses
-- DELETE FROM PAUSE;

-- Format : 'HH24:MI' signifie Heures (0-23) et Minutes
-- INSERT INTO PAUSE VALUES (1, 1, 100, TO_DATE('08:15', 'HH24:MI'), TO_DATE('09:30', 'HH24:MI')); 
-- INSERT INTO PAUSE VALUES (2, 2, 60, TO_DATE('12:00', 'HH24:MI'), TO_DATE('13:00', 'HH24:MI')); 

-- DROP SEQUENCE SEQ_PAUSE;
-- CREATE SEQUENCE SEQ_PAUSE START WITH 3 INCREMENT BY 1 NOCACHE;

COMMIT;