-- ==========================================
-- NETTOYAGE COMPLET
-- ==========================================
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW VUE_DEGAT_COUT';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE REPARATION CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEGAT CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MATERIAU CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DOMMAGE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PAUSE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CHEMIN CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE POINT CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DOMMAGE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PAUSE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CHEMIN';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_POINT';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MATERIAU';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DEGAT';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_REPARATION';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- ==========================================
-- CRÉATION DES SÉQUENCES
-- ==========================================
CREATE SEQUENCE SEQ_POINT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CHEMIN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DOMMAGE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAUSE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MATERIAU START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DEGAT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REPARATION START WITH 1 INCREMENT BY 1 NOCACHE;

-- ==========================================
-- CRÉATION DES TABLES
-- ==========================================

-- Table des Lieux
CREATE TABLE POINT (
    id NUMBER PRIMARY KEY,
    nom VARCHAR2(100) NOT NULL
);

-- Table des Chemins (Routes)
CREATE TABLE CHEMIN (
    id NUMBER PRIMARY KEY,
    nom VARCHAR2(100) NOT NULL,
    point_debut_id NUMBER NOT NULL REFERENCES POINT(id),
    point_fin_id NUMBER NOT NULL REFERENCES POINT(id),
    distance_km NUMBER(10, 2) NOT NULL,
    largeur_m NUMBER(5, 2) NOT NULL,
    sens VARCHAR2(20) NOT NULL CHECK (sens IN ('SIMPLE', 'DOUBLE'))
);

-- Table des Dommages
CREATE TABLE DOMMAGE (
    id NUMBER PRIMARY KEY,
    chemin_id NUMBER NOT NULL REFERENCES CHEMIN(id),
    debut_km NUMBER(10, 2) NOT NULL,
    fin_km NUMBER(10, 2) NOT NULL,
    reduction_taux NUMBER(5, 2) NOT NULL,
    CHECK (debut_km < fin_km)
);

-- Table des Pauses
CREATE TABLE PAUSE (
    id NUMBER PRIMARY KEY,
    chemin_id NUMBER NOT NULL REFERENCES CHEMIN(id),
    point_km NUMBER(10, 2) NOT NULL,
    heure_debut DATE NOT NULL,
    heure_fin DATE NOT NULL,
    CHECK (heure_debut < heure_fin)
);

-- Table des Matériaux
CREATE TABLE MATERIAU (
    id NUMBER PRIMARY KEY,
    nom VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(200)
);

-- Table des Dégâts (avec matériau optionnel si déjà décidé)
CREATE TABLE DEGAT (
    id NUMBER PRIMARY KEY,
    chemin_id NUMBER NOT NULL REFERENCES CHEMIN(id),
    point_km NUMBER(10, 2) NOT NULL,
    surface_m2 NUMBER(10, 2) NOT NULL,
    profondeur_m NUMBER(10, 2) NOT NULL,
    materiau_id NUMBER REFERENCES MATERIAU(id)
);

-- Table des Réparations (intervalles + prix par matériau)
CREATE TABLE REPARATION (
    id NUMBER PRIMARY KEY,
    materiau_id NUMBER NOT NULL REFERENCES MATERIAU(id),
    profondeur_min NUMBER(10, 2) NOT NULL CHECK (profondeur_min >= 0),
    profondeur_max NUMBER(10, 2) NOT NULL,
    prix_par_m2 NUMBER(10, 2) NOT NULL CHECK (prix_par_m2 > 0),
    description VARCHAR2(200),
    CHECK (profondeur_max > profondeur_min),
    UNIQUE (materiau_id, profondeur_min, profondeur_max)
);

-- ==========================================
-- VUE POUR CALCULER LES COÛTS DE RÉPARATION
-- ==========================================

CREATE OR REPLACE VIEW VUE_DEGAT_COUT AS
SELECT 
    d.id AS degat_id,
    d.chemin_id,
    ch.nom AS nom_chemin,
    d.point_km,
    d.surface_m2,
    d.profondeur_m,
    m.id AS materiau_id,
    m.nom AS materiau_nom,
    r.id AS reparation_id,
    r.profondeur_min,
    r.profondeur_max,
    r.prix_par_m2,
    r.description,
    (d.surface_m2 * r.prix_par_m2) AS cout_reparation
FROM DEGAT d
INNER JOIN CHEMIN ch ON d.chemin_id = ch.id
LEFT JOIN MATERIAU m ON d.materiau_id = m.id
LEFT JOIN REPARATION r ON r.materiau_id = d.materiau_id
    AND d.profondeur_m >= r.profondeur_min 
    AND d.profondeur_m < r.profondeur_max;
